# integrations/app.py
import streamlit as st
import os
import tempfile
from main import process_query

# --- Streamlit App Setup ---
st.set_page_config(page_title="FinOps Agentic AI", layout="wide")
st.title("💰 FinOps Agentic AI System")

st.markdown(
    """
    Upload your CSV data file and ask questions about cloud spend, trends, or usage.
    The system will analyze the data and respond intelligently.
    """
)

# --- File Uploader ---
uploaded_file = st.file_uploader("📂 Upload your FinOps data (CSV format)", type=["csv"])

# --- Query Input ---
user_query = st.text_input("💬 Ask a question (e.g. 'Show monthly cost trend')")

# 🔥 DEBUG: Show what was captured
if user_query:
    st.write(f"**DEBUG - Captured Query:** `{user_query}`")

if uploaded_file and user_query:
    with st.spinner("Processing your query... ⏳"):
        # Save uploaded file temporarily
        temp_dir = tempfile.mkdtemp()
        csv_path = os.path.join(temp_dir, uploaded_file.name)
        with open(csv_path, "wb") as f:
            f.write(uploaded_file.getbuffer())

        # 🔥 DEBUG: Print what's being sent
        st.write("🔄 Running agent pipeline...")
        st.write(f"**DEBUG - Query being sent:** `{user_query}`")
        st.write(f"**DEBUG - CSV path:** `{csv_path}`")
        
        # Run pipeline
        result = process_query(user_query, csv_path)  # ← Make sure user_query is passed

        # Debug output
        with st.expander("🔍 Debug Info"):
            st.write(f"Result type: {type(result)}")
            st.write(f"Result keys: {list(result.keys()) if isinstance(result, dict) else 'Not a dict'}")
            st.write(f"Response type: {type(result.get('response', 'N/A'))}")
            st.write(f"Response length: {len(str(result.get('response', '')))}")

        # Extract response safely
        response_text = result.get("response")
        
        # Display response
        st.subheader("🧠 Agent Response")
        
        if response_text and response_text != "None" and str(response_text).strip():
            response_display = str(response_text).strip()
            st.markdown(response_display)
        else:
            st.warning("⚠️ No response was generated by the pipeline.")
            st.info("Check the debug info above for details.")

        # Display chart if any
        chart_path = result.get("chart_path")
        if chart_path and os.path.exists(chart_path):
            st.subheader("📊 Visualization")
            st.image(chart_path, caption="Generated Trend Chart", use_column_width=True)
        elif chart_path:
            st.warning(f"Chart path provided but file not found: {chart_path}")

        # Show file details
        st.info(f"📁 File processed from: {csv_path}")

else:
    st.info("👆 Please upload a CSV and enter a question to start.")

# Optional: footer
st.markdown("---")
st.caption("Built with 🧠 LangGraph + Groq + Streamlit")